add support for more gpus and x86

diff --git a/batman b/batman
--- a/batman
+++ b/batman
@@ -41,7 +41,21 @@ esac
 CORE_FIRST=$(awk '$1 == "processor" {print $3; exit}' /proc/cpuinfo)
 CORE_LAST=$(awk '$1 == "processor" {print $3}' /proc/cpuinfo | tail -1)
 UIDS=$(ls /run/user | head -1)
-DEFAULT_GOVERNOR=$(</sys/devices/system/cpu/cpu0/cpufreq/scaling_governor)
+
+# x86 cpus have powersave and performance governors, check architecture and set the governor accordingly.
+if [ "$(uname -m)" = "x86_64" ] || [ "$(uname -m)" = "i686" ]; then
+
+   if grep "performance" /sys/devices/system/cpu/cpu$CORE_FIRST/cpufreq/scaling_available_governors &> /dev/null; then
+      DEFAULT_GOVERNOR="performance"
+   else
+      echo "can't find the right governor. exiting"
+      exit 0
+   fi
+
+else
+      DEFAULT_GOVERNOR=$(</sys/devices/system/cpu/cpu$CORE_FIRST/cpufreq/scaling_governor)
+fi
+
 AVUSER=$(ls /run/user | wc -l)
 AVPOL=$(ls /sys/devices/system/cpu/cpufreq | grep -c policy)
 FIRSTPOL=$(ls /sys/devices/system/cpu/cpufreq | grep policy | head -1)
@@ -91,6 +105,22 @@ else
    exit 0
 fi
 
+# Check if Phosh/sxmo has started. if not wait a bit and retry.
+if [ "$WLROOTS" == "true" ]; then
+   while [[ true ]]
+   do
+      XDG_RUNTIME_DIR=/run/user/$UIDS/ wlr-randr &> /dev/null
+
+      if [ $? -eq 0 ]; then
+         # If the exit status is 0, break out of the loop
+         break
+      else
+         # If the exit status is not 0, wait for some time and try again
+         sleep 1
+      fi
+   done
+fi
+
 # Check if system is using KDE Plasma.
 if [[ $(which kscreen-doctor) ]]; then
 
@@ -123,7 +153,7 @@ fi
 
 # Use our AVPOL variable to make sure our device has more than one policy groups.
 # If there was only one set the variable to not offline any cpu cores.
-if [[ "$AVPOL" -eq "1" ]]; then
+if [[ "$AVPOL" -eq "1" ]] || [[ "$(uname -m)" = "x86_64" ]] || [[ "$(uname -m)" = "i686" ]]; then
    OFFLINE=false
 fi
 
@@ -147,12 +177,52 @@ if [ -z "$GPUSAVE" ]; then
    GPUSAVE=true
 fi
 
-# DEFAULT_GPU_GOVERNOR will get the default gpu governor.
-# Check if gpu governor file exists.
-if [ ! -d /sys/kernel/gpu/gpu_governor ]; then
-   GPUSAVE=false
-elif [ "$GPUSAVE" == "true" ]; then
+# Check if we can find any GPU profile in devfreq.
+if [ -d /sys/class/devfreq ]; then
+   DEVFREQ_PATH=$(find /sys/class/devfreq -name "*.gpu" -print -quit)
+fi
+
+# Check if GPU governor file exists in different paths if not give up and disable GPU powersaving.
+if [ -f /sys/class/kgsl/kgsl-3d0/devfreq/governor ]; then
+   GPUSAVE=true
+   DEFAULT_GPU_GOVERNOR=$(</sys/class/kgsl/kgsl-3d0/devfreq/governor)
+   GPU_GOVERNOR_PATH="/sys/class/kgsl/kgsl-3d0/devfreq/governor"
+elif [ -f /sys/class/kgsl/kgsl-3d0/governor ]; then
+   GPUSAVE=true
+   DEFAULT_GPU_GOVERNOR=$(</sys/class/kgsl/kgsl-3d0/governor)
+   GPU_GOVERNOR_PATH="/sys/class/kgsl/kgsl-3d0/governor"
+elif [ -f /sys/class/devfreq/1c00000.qcom,kgsl-3d0/governor ]; then
+   GPUSAVE=true
+   DEFAULT_GPU_GOVERNOR=$(</sys/class/devfreq/1c00000.qcom,kgsl-3d0/governor)
+   GPU_GOVERNOR_PATH="/sys/class/devfreq/1c00000.qcom,kgsl-3d0/governor"
+elif [ -f /sys/class/devfreq/ddr_devfreq/governor ]; then
+   GPUSAVE=true
+   DEFAULT_GPU_GOVERNOR=$(</sys/class/devfreq/ddr_devfreq/governor)
+   GPU_GOVERNOR_PATH="/sys/class/devfreq/ddr_devfreq/governor"
+elif [ -f /sys/class/devfreq/graphics/governor ]; then
+   GPUSAVE=true
+   DEFAULT_GPU_GOVERNOR=$(</sys/class/devfreq/graphics/governor)
+   GPU_GOVERNOR_PATH="/sys/class/devfreq/graphics/governor"
+elif [ -f $DEVFREQ/governor ]; then
+   GPUSAVE=true
+   DEFAULT_GPU_GOVERNOR=$(<$DEVFREQ/governor)
+   GPU_GOVERNOR_PATH="$DEVFREQ/governor"
+elif [ -f /sys/kernel/gpu/gpu_governor ]; then
+   GPUSAVE=true
    DEFAULT_GPU_GOVERNOR=$(</sys/kernel/gpu/gpu_governor)
+   GPU_GOVERNOR_PATH="/sys/kernel/gpu/gpu_governor"
+else
+   GPUSAVE=false
+fi
+
+if [ $GPUSAVE == "true" ]; then
+
+   if grep "powersave" $GPU_GOVERNOR_PATH &> /dev/null; then
+      true
+   else
+      GPUSAVE=false
+   fi
+
 fi
 
 # Copy default governor to a file to use it later on if the service gets restarted unexpectedly.
@@ -160,6 +230,7 @@ if [[ "$UPTIME" -le "1" ]]; then
 
    if [ "$DEFAULT_GOVERNOR" == "powersave" ]; then
       echo "bad starting governor. exiting"
+      exit 0
    else
       echo $DEFAULT_GOVERNOR > /var/lib/batman/default_cpu_governor
    fi
@@ -212,12 +283,12 @@ function online() {
     done
 }
 
-# Check if gpu governor file exists if so add gpusave function to change the governor.
+# Check if GPU governor file exists if so add gpusave function to change the governor.
 # Basic function that sets gpu back to its default governor.
 if [ "$GPUSAVE" == "true" ]; then
 
    function gpusave() {
-       echo $DEFAULT_GPU_GOVERNOR > /sys/kernel/gpu/gpu_governor
+       echo $DEFAULT_GPU_GOVERNOR > $GPU_GOVERNOR_PATH
    }
 
 else
@@ -228,12 +299,12 @@ else
 
 fi
 
-# Check if gpu governor file exists if so add gpudefault function to change the governor.
+# Check if GPU governor file exists if so add gpudefault function to change the governor.
 # Basic function that sets gpu back to its default governor.
 if [ "$GPUSAVE" == "true" ]; then
 
    function gpudefault() {
-       echo $DEFAULT_GPU_GOVERNOR > /sys/kernel/gpu/gpu_governor
+       echo $DEFAULT_GPU_GOVERNOR > $GPU_GOVERNOR_PATH
    }
 
 else
